#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyCuaHangTraSua")]
	public partial class QuanLyCuaHangTraSuaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertNGUYENLIEU(NGUYENLIEU instance);
    partial void UpdateNGUYENLIEU(NGUYENLIEU instance);
    partial void DeleteNGUYENLIEU(NGUYENLIEU instance);
    partial void InsertCHITIET_HOADON(CHITIET_HOADON instance);
    partial void UpdateCHITIET_HOADON(CHITIET_HOADON instance);
    partial void DeleteCHITIET_HOADON(CHITIET_HOADON instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertLOAIKH(LOAIKH instance);
    partial void UpdateLOAIKH(LOAIKH instance);
    partial void DeleteLOAIKH(LOAIKH instance);
    partial void InsertNHACUNGCAP(NHACUNGCAP instance);
    partial void UpdateNHACUNGCAP(NHACUNGCAP instance);
    partial void DeleteNHACUNGCAP(NHACUNGCAP instance);
    partial void InsertNHANVIEN(NHANVIEN instance);
    partial void UpdateNHANVIEN(NHANVIEN instance);
    partial void DeleteNHANVIEN(NHANVIEN instance);
    partial void InsertTAIKHOAN(TAIKHOAN instance);
    partial void UpdateTAIKHOAN(TAIKHOAN instance);
    partial void DeleteTAIKHOAN(TAIKHOAN instance);
    partial void InsertTHANHVIEN(THANHVIEN instance);
    partial void UpdateTHANHVIEN(THANHVIEN instance);
    partial void DeleteTHANHVIEN(THANHVIEN instance);
    partial void InsertTRASUA(TRASUA instance);
    partial void UpdateTRASUA(TRASUA instance);
    partial void DeleteTRASUA(TRASUA instance);
    #endregion
		
		public QuanLyCuaHangTraSuaDataContext() : 
				base(global::WindowsFormsApp1.Properties.Settings.Default.QuanLyCuaHangTraSuaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyCuaHangTraSuaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyCuaHangTraSuaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyCuaHangTraSuaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QuanLyCuaHangTraSuaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this.GetTable<NGUYENLIEU>();
			}
		}
		
		public System.Data.Linq.Table<CHITIET_HOADON> CHITIET_HOADONs
		{
			get
			{
				return this.GetTable<CHITIET_HOADON>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<LOAIKH> LOAIKHs
		{
			get
			{
				return this.GetTable<LOAIKH>();
			}
		}
		
		public System.Data.Linq.Table<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this.GetTable<NHACUNGCAP>();
			}
		}
		
		public System.Data.Linq.Table<NHANVIEN> NHANVIENs
		{
			get
			{
				return this.GetTable<NHANVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TAIKHOAN> TAIKHOANs
		{
			get
			{
				return this.GetTable<TAIKHOAN>();
			}
		}
		
		public System.Data.Linq.Table<THANHVIEN> THANHVIENs
		{
			get
			{
				return this.GetTable<THANHVIEN>();
			}
		}
		
		public System.Data.Linq.Table<TRASUA> TRASUAs
		{
			get
			{
				return this.GetTable<TRASUA>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_TimMaSP")]
		public ISingleResult<SP_TimMaSPResult> SP_TimMaSP([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((ISingleResult<SP_TimMaSPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DangNhap")]
		public ISingleResult<SP_DangNhapResult> SP_DangNhap([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Username", DbType="VarChar(6)")] string username, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Password", DbType="VarChar(255)")] string password)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), username, password);
			return ((ISingleResult<SP_DangNhapResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LayDSNCC")]
		public ISingleResult<SP_LayDSNCCResult> SP_LayDSNCC()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_LayDSNCCResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LayDSSP")]
		public ISingleResult<SP_LayDSSPResult> SP_LayDSSP()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<SP_LayDSSPResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_KiemTraMatHang")]
		public ISingleResult<SP_KiemTraMatHangResult> SP_KiemTraMatHang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tenncc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string mathang)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tenncc, mathang);
			return ((ISingleResult<SP_KiemTraMatHangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_BanHang")]
		public ISingleResult<SP_BanHangResult> SP_BanHang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NVarChar(255)")] string tentrasua)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tentrasua);
			return ((ISingleResult<SP_BanHangResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_HienThiChiTietHoaDon")]
		public ISingleResult<SP_HienThiChiTietHoaDonResult> SP_HienThiChiTietHoaDon([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(6)")] string mahoadon)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), mahoadon);
			return ((ISingleResult<SP_HienThiChiTietHoaDonResult>)(result.ReturnValue));
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NGUYENLIEU")]
	public partial class NGUYENLIEU : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NGUYENLIEU_MANL;
		
		private string _NGUYENLIEU_TEN;
		
		private System.DateTime _NGUYENLIEU_NGAYNHAP;
		
		private System.DateTime _NGUYENLIEU_HANSD;
		
		private System.Nullable<int> _NGUYENLIEU_SOLUONGTON;
		
		private string _NGUYENLIEU_MOTA;
		
		private System.Nullable<byte> _NGUYENLIEU_TRANGTHAI;
		
		private string _NGUYENLIEU_MANCC;
		
		private EntityRef<NHACUNGCAP> _NHACUNGCAP;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNGUYENLIEU_MANLChanging(string value);
    partial void OnNGUYENLIEU_MANLChanged();
    partial void OnNGUYENLIEU_TENChanging(string value);
    partial void OnNGUYENLIEU_TENChanged();
    partial void OnNGUYENLIEU_NGAYNHAPChanging(System.DateTime value);
    partial void OnNGUYENLIEU_NGAYNHAPChanged();
    partial void OnNGUYENLIEU_HANSDChanging(System.DateTime value);
    partial void OnNGUYENLIEU_HANSDChanged();
    partial void OnNGUYENLIEU_SOLUONGTONChanging(System.Nullable<int> value);
    partial void OnNGUYENLIEU_SOLUONGTONChanged();
    partial void OnNGUYENLIEU_MOTAChanging(string value);
    partial void OnNGUYENLIEU_MOTAChanged();
    partial void OnNGUYENLIEU_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnNGUYENLIEU_TRANGTHAIChanged();
    partial void OnNGUYENLIEU_MANCCChanging(string value);
    partial void OnNGUYENLIEU_MANCCChanged();
    #endregion
		
		public NGUYENLIEU()
		{
			this._NHACUNGCAP = default(EntityRef<NHACUNGCAP>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_MANL", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NGUYENLIEU_MANL
		{
			get
			{
				return this._NGUYENLIEU_MANL;
			}
			set
			{
				if ((this._NGUYENLIEU_MANL != value))
				{
					this.OnNGUYENLIEU_MANLChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_MANL = value;
					this.SendPropertyChanged("NGUYENLIEU_MANL");
					this.OnNGUYENLIEU_MANLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_TEN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NGUYENLIEU_TEN
		{
			get
			{
				return this._NGUYENLIEU_TEN;
			}
			set
			{
				if ((this._NGUYENLIEU_TEN != value))
				{
					this.OnNGUYENLIEU_TENChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_TEN = value;
					this.SendPropertyChanged("NGUYENLIEU_TEN");
					this.OnNGUYENLIEU_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_NGAYNHAP", DbType="DateTime NOT NULL")]
		public System.DateTime NGUYENLIEU_NGAYNHAP
		{
			get
			{
				return this._NGUYENLIEU_NGAYNHAP;
			}
			set
			{
				if ((this._NGUYENLIEU_NGAYNHAP != value))
				{
					this.OnNGUYENLIEU_NGAYNHAPChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_NGAYNHAP = value;
					this.SendPropertyChanged("NGUYENLIEU_NGAYNHAP");
					this.OnNGUYENLIEU_NGAYNHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_HANSD", DbType="DateTime NOT NULL")]
		public System.DateTime NGUYENLIEU_HANSD
		{
			get
			{
				return this._NGUYENLIEU_HANSD;
			}
			set
			{
				if ((this._NGUYENLIEU_HANSD != value))
				{
					this.OnNGUYENLIEU_HANSDChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_HANSD = value;
					this.SendPropertyChanged("NGUYENLIEU_HANSD");
					this.OnNGUYENLIEU_HANSDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_SOLUONGTON", DbType="Int")]
		public System.Nullable<int> NGUYENLIEU_SOLUONGTON
		{
			get
			{
				return this._NGUYENLIEU_SOLUONGTON;
			}
			set
			{
				if ((this._NGUYENLIEU_SOLUONGTON != value))
				{
					this.OnNGUYENLIEU_SOLUONGTONChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_SOLUONGTON = value;
					this.SendPropertyChanged("NGUYENLIEU_SOLUONGTON");
					this.OnNGUYENLIEU_SOLUONGTONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_MOTA", DbType="NVarChar(100)")]
		public string NGUYENLIEU_MOTA
		{
			get
			{
				return this._NGUYENLIEU_MOTA;
			}
			set
			{
				if ((this._NGUYENLIEU_MOTA != value))
				{
					this.OnNGUYENLIEU_MOTAChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_MOTA = value;
					this.SendPropertyChanged("NGUYENLIEU_MOTA");
					this.OnNGUYENLIEU_MOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> NGUYENLIEU_TRANGTHAI
		{
			get
			{
				return this._NGUYENLIEU_TRANGTHAI;
			}
			set
			{
				if ((this._NGUYENLIEU_TRANGTHAI != value))
				{
					this.OnNGUYENLIEU_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_TRANGTHAI = value;
					this.SendPropertyChanged("NGUYENLIEU_TRANGTHAI");
					this.OnNGUYENLIEU_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGUYENLIEU_MANCC", DbType="VarChar(6)")]
		public string NGUYENLIEU_MANCC
		{
			get
			{
				return this._NGUYENLIEU_MANCC;
			}
			set
			{
				if ((this._NGUYENLIEU_MANCC != value))
				{
					if (this._NHACUNGCAP.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNGUYENLIEU_MANCCChanging(value);
					this.SendPropertyChanging();
					this._NGUYENLIEU_MANCC = value;
					this.SendPropertyChanged("NGUYENLIEU_MANCC");
					this.OnNGUYENLIEU_MANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NHACUNGCAP", ThisKey="NGUYENLIEU_MANCC", OtherKey="NHACUNGCAP_MANCC", IsForeignKey=true)]
		public NHACUNGCAP NHACUNGCAP
		{
			get
			{
				return this._NHACUNGCAP.Entity;
			}
			set
			{
				NHACUNGCAP previousValue = this._NHACUNGCAP.Entity;
				if (((previousValue != value) 
							|| (this._NHACUNGCAP.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHACUNGCAP.Entity = null;
						previousValue.NGUYENLIEUs.Remove(this);
					}
					this._NHACUNGCAP.Entity = value;
					if ((value != null))
					{
						value.NGUYENLIEUs.Add(this);
						this._NGUYENLIEU_MANCC = value.NHACUNGCAP_MANCC;
					}
					else
					{
						this._NGUYENLIEU_MANCC = default(string);
					}
					this.SendPropertyChanged("NHACUNGCAP");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIET_HOADON")]
	public partial class CHITIET_HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CHITIET_HOADON_MAHOADON;
		
		private string _CHITIET_HOADON_MATS;
		
		private string _CHITIET_HOADON_TENSP;
		
		private System.Nullable<char> _CHITIET_HOADON_SIZE;
		
		private int _CHITIET_HOADON_SOLUONG;
		
		private decimal _CHITIET_HOADON_DONGIA;
		
		private EntityRef<HOADON> _HOADON;
		
		private EntityRef<TRASUA> _TRASUA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCHITIET_HOADON_MAHOADONChanging(string value);
    partial void OnCHITIET_HOADON_MAHOADONChanged();
    partial void OnCHITIET_HOADON_MATSChanging(string value);
    partial void OnCHITIET_HOADON_MATSChanged();
    partial void OnCHITIET_HOADON_TENSPChanging(string value);
    partial void OnCHITIET_HOADON_TENSPChanged();
    partial void OnCHITIET_HOADON_SIZEChanging(System.Nullable<char> value);
    partial void OnCHITIET_HOADON_SIZEChanged();
    partial void OnCHITIET_HOADON_SOLUONGChanging(int value);
    partial void OnCHITIET_HOADON_SOLUONGChanged();
    partial void OnCHITIET_HOADON_DONGIAChanging(decimal value);
    partial void OnCHITIET_HOADON_DONGIAChanged();
    #endregion
		
		public CHITIET_HOADON()
		{
			this._HOADON = default(EntityRef<HOADON>);
			this._TRASUA = default(EntityRef<TRASUA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_MAHOADON", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CHITIET_HOADON_MAHOADON
		{
			get
			{
				return this._CHITIET_HOADON_MAHOADON;
			}
			set
			{
				if ((this._CHITIET_HOADON_MAHOADON != value))
				{
					if (this._HOADON.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCHITIET_HOADON_MAHOADONChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_MAHOADON = value;
					this.SendPropertyChanged("CHITIET_HOADON_MAHOADON");
					this.OnCHITIET_HOADON_MAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_MATS", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CHITIET_HOADON_MATS
		{
			get
			{
				return this._CHITIET_HOADON_MATS;
			}
			set
			{
				if ((this._CHITIET_HOADON_MATS != value))
				{
					if (this._TRASUA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnCHITIET_HOADON_MATSChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_MATS = value;
					this.SendPropertyChanged("CHITIET_HOADON_MATS");
					this.OnCHITIET_HOADON_MATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_TENSP", DbType="NVarChar(100)")]
		public string CHITIET_HOADON_TENSP
		{
			get
			{
				return this._CHITIET_HOADON_TENSP;
			}
			set
			{
				if ((this._CHITIET_HOADON_TENSP != value))
				{
					this.OnCHITIET_HOADON_TENSPChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_TENSP = value;
					this.SendPropertyChanged("CHITIET_HOADON_TENSP");
					this.OnCHITIET_HOADON_TENSPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_SIZE", DbType="Char(1)")]
		public System.Nullable<char> CHITIET_HOADON_SIZE
		{
			get
			{
				return this._CHITIET_HOADON_SIZE;
			}
			set
			{
				if ((this._CHITIET_HOADON_SIZE != value))
				{
					this.OnCHITIET_HOADON_SIZEChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_SIZE = value;
					this.SendPropertyChanged("CHITIET_HOADON_SIZE");
					this.OnCHITIET_HOADON_SIZEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_SOLUONG", DbType="Int NOT NULL")]
		public int CHITIET_HOADON_SOLUONG
		{
			get
			{
				return this._CHITIET_HOADON_SOLUONG;
			}
			set
			{
				if ((this._CHITIET_HOADON_SOLUONG != value))
				{
					this.OnCHITIET_HOADON_SOLUONGChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_SOLUONG = value;
					this.SendPropertyChanged("CHITIET_HOADON_SOLUONG");
					this.OnCHITIET_HOADON_SOLUONGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_DONGIA", DbType="Money NOT NULL")]
		public decimal CHITIET_HOADON_DONGIA
		{
			get
			{
				return this._CHITIET_HOADON_DONGIA;
			}
			set
			{
				if ((this._CHITIET_HOADON_DONGIA != value))
				{
					this.OnCHITIET_HOADON_DONGIAChanging(value);
					this.SendPropertyChanging();
					this._CHITIET_HOADON_DONGIA = value;
					this.SendPropertyChanged("CHITIET_HOADON_DONGIA");
					this.OnCHITIET_HOADON_DONGIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIET_HOADON", Storage="_HOADON", ThisKey="CHITIET_HOADON_MAHOADON", OtherKey="HOADON_MAHOADON", IsForeignKey=true)]
		public HOADON HOADON
		{
			get
			{
				return this._HOADON.Entity;
			}
			set
			{
				HOADON previousValue = this._HOADON.Entity;
				if (((previousValue != value) 
							|| (this._HOADON.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._HOADON.Entity = null;
						previousValue.CHITIET_HOADONs.Remove(this);
					}
					this._HOADON.Entity = value;
					if ((value != null))
					{
						value.CHITIET_HOADONs.Add(this);
						this._CHITIET_HOADON_MAHOADON = value.HOADON_MAHOADON;
					}
					else
					{
						this._CHITIET_HOADON_MAHOADON = default(string);
					}
					this.SendPropertyChanged("HOADON");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRASUA_CHITIET_HOADON", Storage="_TRASUA", ThisKey="CHITIET_HOADON_MATS", OtherKey="TRASUA_MATS", IsForeignKey=true)]
		public TRASUA TRASUA
		{
			get
			{
				return this._TRASUA.Entity;
			}
			set
			{
				TRASUA previousValue = this._TRASUA.Entity;
				if (((previousValue != value) 
							|| (this._TRASUA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TRASUA.Entity = null;
						previousValue.CHITIET_HOADONs.Remove(this);
					}
					this._TRASUA.Entity = value;
					if ((value != null))
					{
						value.CHITIET_HOADONs.Add(this);
						this._CHITIET_HOADON_MATS = value.TRASUA_MATS;
					}
					else
					{
						this._CHITIET_HOADON_MATS = default(string);
					}
					this.SendPropertyChanged("TRASUA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _HOADON_MAHOADON;
		
		private System.DateTime _HOADON_NGAYLAP;
		
		private System.Nullable<byte> _HOADON_TRANGTHAI;
		
		private System.Nullable<decimal> _HOADON_KHACHTRA;
		
		private System.Nullable<decimal> _HOADON_THANHTIEN;
		
		private System.Nullable<decimal> _HOADON_THOILAI;
		
		private string _HOADON_MAKH;
		
		private string _HOADON_MANV;
		
		private string _HOADON_PTTHANHTOAN;
		
		private System.Nullable<int> _DIEMTICHLUY;
		
		private EntitySet<CHITIET_HOADON> _CHITIET_HOADONs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHOADON_MAHOADONChanging(string value);
    partial void OnHOADON_MAHOADONChanged();
    partial void OnHOADON_NGAYLAPChanging(System.DateTime value);
    partial void OnHOADON_NGAYLAPChanged();
    partial void OnHOADON_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnHOADON_TRANGTHAIChanged();
    partial void OnHOADON_KHACHTRAChanging(System.Nullable<decimal> value);
    partial void OnHOADON_KHACHTRAChanged();
    partial void OnHOADON_THANHTIENChanging(System.Nullable<decimal> value);
    partial void OnHOADON_THANHTIENChanged();
    partial void OnHOADON_THOILAIChanging(System.Nullable<decimal> value);
    partial void OnHOADON_THOILAIChanged();
    partial void OnHOADON_MAKHChanging(string value);
    partial void OnHOADON_MAKHChanged();
    partial void OnHOADON_MANVChanging(string value);
    partial void OnHOADON_MANVChanged();
    partial void OnHOADON_PTTHANHTOANChanging(string value);
    partial void OnHOADON_PTTHANHTOANChanged();
    partial void OnDIEMTICHLUYChanging(System.Nullable<int> value);
    partial void OnDIEMTICHLUYChanged();
    #endregion
		
		public HOADON()
		{
			this._CHITIET_HOADONs = new EntitySet<CHITIET_HOADON>(new Action<CHITIET_HOADON>(this.attach_CHITIET_HOADONs), new Action<CHITIET_HOADON>(this.detach_CHITIET_HOADONs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_MAHOADON", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string HOADON_MAHOADON
		{
			get
			{
				return this._HOADON_MAHOADON;
			}
			set
			{
				if ((this._HOADON_MAHOADON != value))
				{
					this.OnHOADON_MAHOADONChanging(value);
					this.SendPropertyChanging();
					this._HOADON_MAHOADON = value;
					this.SendPropertyChanged("HOADON_MAHOADON");
					this.OnHOADON_MAHOADONChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_NGAYLAP", DbType="DateTime NOT NULL")]
		public System.DateTime HOADON_NGAYLAP
		{
			get
			{
				return this._HOADON_NGAYLAP;
			}
			set
			{
				if ((this._HOADON_NGAYLAP != value))
				{
					this.OnHOADON_NGAYLAPChanging(value);
					this.SendPropertyChanging();
					this._HOADON_NGAYLAP = value;
					this.SendPropertyChanged("HOADON_NGAYLAP");
					this.OnHOADON_NGAYLAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> HOADON_TRANGTHAI
		{
			get
			{
				return this._HOADON_TRANGTHAI;
			}
			set
			{
				if ((this._HOADON_TRANGTHAI != value))
				{
					this.OnHOADON_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._HOADON_TRANGTHAI = value;
					this.SendPropertyChanged("HOADON_TRANGTHAI");
					this.OnHOADON_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_KHACHTRA", DbType="Money")]
		public System.Nullable<decimal> HOADON_KHACHTRA
		{
			get
			{
				return this._HOADON_KHACHTRA;
			}
			set
			{
				if ((this._HOADON_KHACHTRA != value))
				{
					this.OnHOADON_KHACHTRAChanging(value);
					this.SendPropertyChanging();
					this._HOADON_KHACHTRA = value;
					this.SendPropertyChanged("HOADON_KHACHTRA");
					this.OnHOADON_KHACHTRAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_THANHTIEN", DbType="Money")]
		public System.Nullable<decimal> HOADON_THANHTIEN
		{
			get
			{
				return this._HOADON_THANHTIEN;
			}
			set
			{
				if ((this._HOADON_THANHTIEN != value))
				{
					this.OnHOADON_THANHTIENChanging(value);
					this.SendPropertyChanging();
					this._HOADON_THANHTIEN = value;
					this.SendPropertyChanged("HOADON_THANHTIEN");
					this.OnHOADON_THANHTIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_THOILAI", DbType="Money")]
		public System.Nullable<decimal> HOADON_THOILAI
		{
			get
			{
				return this._HOADON_THOILAI;
			}
			set
			{
				if ((this._HOADON_THOILAI != value))
				{
					this.OnHOADON_THOILAIChanging(value);
					this.SendPropertyChanging();
					this._HOADON_THOILAI = value;
					this.SendPropertyChanged("HOADON_THOILAI");
					this.OnHOADON_THOILAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_MAKH", DbType="VarChar(6)")]
		public string HOADON_MAKH
		{
			get
			{
				return this._HOADON_MAKH;
			}
			set
			{
				if ((this._HOADON_MAKH != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHOADON_MAKHChanging(value);
					this.SendPropertyChanging();
					this._HOADON_MAKH = value;
					this.SendPropertyChanged("HOADON_MAKH");
					this.OnHOADON_MAKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_MANV", DbType="VarChar(6)")]
		public string HOADON_MANV
		{
			get
			{
				return this._HOADON_MANV;
			}
			set
			{
				if ((this._HOADON_MANV != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnHOADON_MANVChanging(value);
					this.SendPropertyChanging();
					this._HOADON_MANV = value;
					this.SendPropertyChanged("HOADON_MANV");
					this.OnHOADON_MANVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HOADON_PTTHANHTOAN", DbType="NVarChar(20)")]
		public string HOADON_PTTHANHTOAN
		{
			get
			{
				return this._HOADON_PTTHANHTOAN;
			}
			set
			{
				if ((this._HOADON_PTTHANHTOAN != value))
				{
					this.OnHOADON_PTTHANHTOANChanging(value);
					this.SendPropertyChanging();
					this._HOADON_PTTHANHTOAN = value;
					this.SendPropertyChanged("HOADON_PTTHANHTOAN");
					this.OnHOADON_PTTHANHTOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTICHLUY", DbType="Int")]
		public System.Nullable<int> DIEMTICHLUY
		{
			get
			{
				return this._DIEMTICHLUY;
			}
			set
			{
				if ((this._DIEMTICHLUY != value))
				{
					this.OnDIEMTICHLUYChanging(value);
					this.SendPropertyChanging();
					this._DIEMTICHLUY = value;
					this.SendPropertyChanged("DIEMTICHLUY");
					this.OnDIEMTICHLUYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HOADON_CHITIET_HOADON", Storage="_CHITIET_HOADONs", ThisKey="HOADON_MAHOADON", OtherKey="CHITIET_HOADON_MAHOADON")]
		public EntitySet<CHITIET_HOADON> CHITIET_HOADONs
		{
			get
			{
				return this._CHITIET_HOADONs;
			}
			set
			{
				this._CHITIET_HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_KHACHHANG", ThisKey="HOADON_MAKH", OtherKey="KHACHHANG_MAKHACH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._HOADON_MAKH = value.KHACHHANG_MAKHACH;
					}
					else
					{
						this._HOADON_MAKH = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_NHANVIEN", ThisKey="HOADON_MANV", OtherKey="NHANVIEN_MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._HOADON_MANV = value.NHANVIEN_MANHANVIEN;
					}
					else
					{
						this._HOADON_MANV = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_HOADONs(CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = this;
		}
		
		private void detach_CHITIET_HOADONs(CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.HOADON = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _KHACHHANG_MAKHACH;
		
		private string _KHACHHANG_HOTENDEM;
		
		private string _KHACHHANG_TEN;
		
		private string _KHACHANG_SODIENTHOAI;
		
		private System.Nullable<System.DateTime> _KHACHANG_NGAYSINH;
		
		private string _KHACHHANG_DIACHI;
		
		private string _KHACHHANG_GIOITINH;
		
		private System.Nullable<byte> _KHACHHANG_TRANGTHAI;
		
		private string _KHACHHANG_LOAIKH;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntityRef<THANHVIEN> _THANHVIEN;
		
		private EntityRef<LOAIKH> _LOAIKH;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnKHACHHANG_MAKHACHChanging(string value);
    partial void OnKHACHHANG_MAKHACHChanged();
    partial void OnKHACHHANG_HOTENDEMChanging(string value);
    partial void OnKHACHHANG_HOTENDEMChanged();
    partial void OnKHACHHANG_TENChanging(string value);
    partial void OnKHACHHANG_TENChanged();
    partial void OnKHACHANG_SODIENTHOAIChanging(string value);
    partial void OnKHACHANG_SODIENTHOAIChanged();
    partial void OnKHACHANG_NGAYSINHChanging(System.Nullable<System.DateTime> value);
    partial void OnKHACHANG_NGAYSINHChanged();
    partial void OnKHACHHANG_DIACHIChanging(string value);
    partial void OnKHACHHANG_DIACHIChanged();
    partial void OnKHACHHANG_GIOITINHChanging(string value);
    partial void OnKHACHHANG_GIOITINHChanged();
    partial void OnKHACHHANG_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnKHACHHANG_TRANGTHAIChanged();
    partial void OnKHACHHANG_LOAIKHChanging(string value);
    partial void OnKHACHHANG_LOAIKHChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._THANHVIEN = default(EntityRef<THANHVIEN>);
			this._LOAIKH = default(EntityRef<LOAIKH>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_MAKHACH", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string KHACHHANG_MAKHACH
		{
			get
			{
				return this._KHACHHANG_MAKHACH;
			}
			set
			{
				if ((this._KHACHHANG_MAKHACH != value))
				{
					this.OnKHACHHANG_MAKHACHChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_MAKHACH = value;
					this.SendPropertyChanged("KHACHHANG_MAKHACH");
					this.OnKHACHHANG_MAKHACHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_HOTENDEM", DbType="NVarChar(100)")]
		public string KHACHHANG_HOTENDEM
		{
			get
			{
				return this._KHACHHANG_HOTENDEM;
			}
			set
			{
				if ((this._KHACHHANG_HOTENDEM != value))
				{
					this.OnKHACHHANG_HOTENDEMChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_HOTENDEM = value;
					this.SendPropertyChanged("KHACHHANG_HOTENDEM");
					this.OnKHACHHANG_HOTENDEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_TEN", DbType="NVarChar(100)")]
		public string KHACHHANG_TEN
		{
			get
			{
				return this._KHACHHANG_TEN;
			}
			set
			{
				if ((this._KHACHHANG_TEN != value))
				{
					this.OnKHACHHANG_TENChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_TEN = value;
					this.SendPropertyChanged("KHACHHANG_TEN");
					this.OnKHACHHANG_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHANG_SODIENTHOAI", DbType="VarChar(10)")]
		public string KHACHANG_SODIENTHOAI
		{
			get
			{
				return this._KHACHANG_SODIENTHOAI;
			}
			set
			{
				if ((this._KHACHANG_SODIENTHOAI != value))
				{
					this.OnKHACHANG_SODIENTHOAIChanging(value);
					this.SendPropertyChanging();
					this._KHACHANG_SODIENTHOAI = value;
					this.SendPropertyChanged("KHACHANG_SODIENTHOAI");
					this.OnKHACHANG_SODIENTHOAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHANG_NGAYSINH", DbType="DateTime")]
		public System.Nullable<System.DateTime> KHACHANG_NGAYSINH
		{
			get
			{
				return this._KHACHANG_NGAYSINH;
			}
			set
			{
				if ((this._KHACHANG_NGAYSINH != value))
				{
					this.OnKHACHANG_NGAYSINHChanging(value);
					this.SendPropertyChanging();
					this._KHACHANG_NGAYSINH = value;
					this.SendPropertyChanged("KHACHANG_NGAYSINH");
					this.OnKHACHANG_NGAYSINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_DIACHI", DbType="NVarChar(200)")]
		public string KHACHHANG_DIACHI
		{
			get
			{
				return this._KHACHHANG_DIACHI;
			}
			set
			{
				if ((this._KHACHHANG_DIACHI != value))
				{
					this.OnKHACHHANG_DIACHIChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_DIACHI = value;
					this.SendPropertyChanged("KHACHHANG_DIACHI");
					this.OnKHACHHANG_DIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_GIOITINH", DbType="NVarChar(10)")]
		public string KHACHHANG_GIOITINH
		{
			get
			{
				return this._KHACHHANG_GIOITINH;
			}
			set
			{
				if ((this._KHACHHANG_GIOITINH != value))
				{
					this.OnKHACHHANG_GIOITINHChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_GIOITINH = value;
					this.SendPropertyChanged("KHACHHANG_GIOITINH");
					this.OnKHACHHANG_GIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> KHACHHANG_TRANGTHAI
		{
			get
			{
				return this._KHACHHANG_TRANGTHAI;
			}
			set
			{
				if ((this._KHACHHANG_TRANGTHAI != value))
				{
					this.OnKHACHHANG_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_TRANGTHAI = value;
					this.SendPropertyChanged("KHACHHANG_TRANGTHAI");
					this.OnKHACHHANG_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KHACHHANG_LOAIKH", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string KHACHHANG_LOAIKH
		{
			get
			{
				return this._KHACHHANG_LOAIKH;
			}
			set
			{
				if ((this._KHACHHANG_LOAIKH != value))
				{
					if (this._LOAIKH.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKHACHHANG_LOAIKHChanging(value);
					this.SendPropertyChanging();
					this._KHACHHANG_LOAIKH = value;
					this.SendPropertyChanged("KHACHHANG_LOAIKH");
					this.OnKHACHHANG_LOAIKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_HOADON", Storage="_HOADONs", ThisKey="KHACHHANG_MAKHACH", OtherKey="HOADON_MAKH")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THANHVIEN", Storage="_THANHVIEN", ThisKey="KHACHHANG_MAKHACH", OtherKey="THANHVIEN_MATV", IsUnique=true, IsForeignKey=false)]
		public THANHVIEN THANHVIEN
		{
			get
			{
				return this._THANHVIEN.Entity;
			}
			set
			{
				THANHVIEN previousValue = this._THANHVIEN.Entity;
				if (((previousValue != value) 
							|| (this._THANHVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THANHVIEN.Entity = null;
						previousValue.KHACHHANG = null;
					}
					this._THANHVIEN.Entity = value;
					if ((value != null))
					{
						value.KHACHHANG = this;
					}
					this.SendPropertyChanged("THANHVIEN");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKH_KHACHHANG", Storage="_LOAIKH", ThisKey="KHACHHANG_LOAIKH", OtherKey="MALOAIKH", IsForeignKey=true)]
		public LOAIKH LOAIKH
		{
			get
			{
				return this._LOAIKH.Entity;
			}
			set
			{
				LOAIKH previousValue = this._LOAIKH.Entity;
				if (((previousValue != value) 
							|| (this._LOAIKH.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIKH.Entity = null;
						previousValue.KHACHHANGs.Remove(this);
					}
					this._LOAIKH.Entity = value;
					if ((value != null))
					{
						value.KHACHHANGs.Add(this);
						this._KHACHHANG_LOAIKH = value.MALOAIKH;
					}
					else
					{
						this._KHACHHANG_LOAIKH = default(string);
					}
					this.SendPropertyChanged("LOAIKH");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIKH")]
	public partial class LOAIKH : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MALOAIKH;
		
		private string _TENLOAIKH;
		
		private System.Nullable<byte> _TRANGTHAI;
		
		private EntitySet<KHACHHANG> _KHACHHANGs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMALOAIKHChanging(string value);
    partial void OnMALOAIKHChanged();
    partial void OnTENLOAIKHChanging(string value);
    partial void OnTENLOAIKHChanged();
    partial void OnTRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnTRANGTHAIChanged();
    #endregion
		
		public LOAIKH()
		{
			this._KHACHHANGs = new EntitySet<KHACHHANG>(new Action<KHACHHANG>(this.attach_KHACHHANGs), new Action<KHACHHANG>(this.detach_KHACHHANGs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MALOAIKH", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MALOAIKH
		{
			get
			{
				return this._MALOAIKH;
			}
			set
			{
				if ((this._MALOAIKH != value))
				{
					this.OnMALOAIKHChanging(value);
					this.SendPropertyChanging();
					this._MALOAIKH = value;
					this.SendPropertyChanged("MALOAIKH");
					this.OnMALOAIKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENLOAIKH", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string TENLOAIKH
		{
			get
			{
				return this._TENLOAIKH;
			}
			set
			{
				if ((this._TENLOAIKH != value))
				{
					this.OnTENLOAIKHChanging(value);
					this.SendPropertyChanging();
					this._TENLOAIKH = value;
					this.SendPropertyChanged("TENLOAIKH");
					this.OnTENLOAIKHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> TRANGTHAI
		{
			get
			{
				return this._TRANGTHAI;
			}
			set
			{
				if ((this._TRANGTHAI != value))
				{
					this.OnTRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRANGTHAI = value;
					this.SendPropertyChanged("TRANGTHAI");
					this.OnTRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIKH_KHACHHANG", Storage="_KHACHHANGs", ThisKey="MALOAIKH", OtherKey="KHACHHANG_LOAIKH")]
		public EntitySet<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this._KHACHHANGs;
			}
			set
			{
				this._KHACHHANGs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKH = this;
		}
		
		private void detach_KHACHHANGs(KHACHHANG entity)
		{
			this.SendPropertyChanging();
			entity.LOAIKH = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHACUNGCAP")]
	public partial class NHACUNGCAP : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NHACUNGCAP_MANCC;
		
		private string _NHACUNGCAP_TEN;
		
		private string _NHACUNGCAP_SDT;
		
		private string _NHACUNGCAP_DIACHI;
		
		private System.Nullable<byte> _NHACUNGCAP_TRANGTHAI;
		
		private string _MANHANVIEN;
		
		private EntitySet<NGUYENLIEU> _NGUYENLIEUs;
		
		private EntityRef<NHANVIEN> _NHANVIEN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNHACUNGCAP_MANCCChanging(string value);
    partial void OnNHACUNGCAP_MANCCChanged();
    partial void OnNHACUNGCAP_TENChanging(string value);
    partial void OnNHACUNGCAP_TENChanged();
    partial void OnNHACUNGCAP_SDTChanging(string value);
    partial void OnNHACUNGCAP_SDTChanged();
    partial void OnNHACUNGCAP_DIACHIChanging(string value);
    partial void OnNHACUNGCAP_DIACHIChanged();
    partial void OnNHACUNGCAP_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnNHACUNGCAP_TRANGTHAIChanged();
    partial void OnMANHANVIENChanging(string value);
    partial void OnMANHANVIENChanged();
    #endregion
		
		public NHACUNGCAP()
		{
			this._NGUYENLIEUs = new EntitySet<NGUYENLIEU>(new Action<NGUYENLIEU>(this.attach_NGUYENLIEUs), new Action<NGUYENLIEU>(this.detach_NGUYENLIEUs));
			this._NHANVIEN = default(EntityRef<NHANVIEN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_MANCC", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NHACUNGCAP_MANCC
		{
			get
			{
				return this._NHACUNGCAP_MANCC;
			}
			set
			{
				if ((this._NHACUNGCAP_MANCC != value))
				{
					this.OnNHACUNGCAP_MANCCChanging(value);
					this.SendPropertyChanging();
					this._NHACUNGCAP_MANCC = value;
					this.SendPropertyChanged("NHACUNGCAP_MANCC");
					this.OnNHACUNGCAP_MANCCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_TEN", DbType="NVarChar(50)")]
		public string NHACUNGCAP_TEN
		{
			get
			{
				return this._NHACUNGCAP_TEN;
			}
			set
			{
				if ((this._NHACUNGCAP_TEN != value))
				{
					this.OnNHACUNGCAP_TENChanging(value);
					this.SendPropertyChanging();
					this._NHACUNGCAP_TEN = value;
					this.SendPropertyChanged("NHACUNGCAP_TEN");
					this.OnNHACUNGCAP_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_SDT", DbType="VarChar(11)")]
		public string NHACUNGCAP_SDT
		{
			get
			{
				return this._NHACUNGCAP_SDT;
			}
			set
			{
				if ((this._NHACUNGCAP_SDT != value))
				{
					this.OnNHACUNGCAP_SDTChanging(value);
					this.SendPropertyChanging();
					this._NHACUNGCAP_SDT = value;
					this.SendPropertyChanged("NHACUNGCAP_SDT");
					this.OnNHACUNGCAP_SDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_DIACHI", DbType="NVarChar(50)")]
		public string NHACUNGCAP_DIACHI
		{
			get
			{
				return this._NHACUNGCAP_DIACHI;
			}
			set
			{
				if ((this._NHACUNGCAP_DIACHI != value))
				{
					this.OnNHACUNGCAP_DIACHIChanging(value);
					this.SendPropertyChanging();
					this._NHACUNGCAP_DIACHI = value;
					this.SendPropertyChanged("NHACUNGCAP_DIACHI");
					this.OnNHACUNGCAP_DIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> NHACUNGCAP_TRANGTHAI
		{
			get
			{
				return this._NHACUNGCAP_TRANGTHAI;
			}
			set
			{
				if ((this._NHACUNGCAP_TRANGTHAI != value))
				{
					this.OnNHACUNGCAP_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._NHACUNGCAP_TRANGTHAI = value;
					this.SendPropertyChanged("NHACUNGCAP_TRANGTHAI");
					this.OnNHACUNGCAP_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MANHANVIEN", DbType="VarChar(6)")]
		public string MANHANVIEN
		{
			get
			{
				return this._MANHANVIEN;
			}
			set
			{
				if ((this._MANHANVIEN != value))
				{
					if (this._NHANVIEN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._MANHANVIEN = value;
					this.SendPropertyChanged("MANHANVIEN");
					this.OnMANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHACUNGCAP_NGUYENLIEU", Storage="_NGUYENLIEUs", ThisKey="NHACUNGCAP_MANCC", OtherKey="NGUYENLIEU_MANCC")]
		public EntitySet<NGUYENLIEU> NGUYENLIEUs
		{
			get
			{
				return this._NGUYENLIEUs;
			}
			set
			{
				this._NGUYENLIEUs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_NHACUNGCAP", Storage="_NHANVIEN", ThisKey="MANHANVIEN", OtherKey="NHANVIEN_MANHANVIEN", IsForeignKey=true)]
		public NHANVIEN NHANVIEN
		{
			get
			{
				return this._NHANVIEN.Entity;
			}
			set
			{
				NHANVIEN previousValue = this._NHANVIEN.Entity;
				if (((previousValue != value) 
							|| (this._NHANVIEN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NHANVIEN.Entity = null;
						previousValue.NHACUNGCAPs.Remove(this);
					}
					this._NHANVIEN.Entity = value;
					if ((value != null))
					{
						value.NHACUNGCAPs.Add(this);
						this._MANHANVIEN = value.NHANVIEN_MANHANVIEN;
					}
					else
					{
						this._MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("NHANVIEN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = this;
		}
		
		private void detach_NGUYENLIEUs(NGUYENLIEU entity)
		{
			this.SendPropertyChanging();
			entity.NHACUNGCAP = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NHANVIEN")]
	public partial class NHANVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _NHANVIEN_MANHANVIEN;
		
		private string _NHANVIEN_HOVATENDEM;
		
		private string _NHANVIEN_TEN;
		
		private string _NHANVIEN_GIOITINH;
		
		private System.Nullable<System.DateTime> _NHANVIEN_NTNS;
		
		private string _NHANVIEN_PHONE;
		
		private string _NHANVIEN_DIACHI;
		
		private System.Nullable<byte> _NHANVIEN_TRANGTHAI;
		
		private string _TAIKHOAN_MANHANVIEN;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<NHACUNGCAP> _NHACUNGCAPs;
		
		private EntityRef<TAIKHOAN> _TAIKHOAN;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNHANVIEN_MANHANVIENChanging(string value);
    partial void OnNHANVIEN_MANHANVIENChanged();
    partial void OnNHANVIEN_HOVATENDEMChanging(string value);
    partial void OnNHANVIEN_HOVATENDEMChanged();
    partial void OnNHANVIEN_TENChanging(string value);
    partial void OnNHANVIEN_TENChanged();
    partial void OnNHANVIEN_GIOITINHChanging(string value);
    partial void OnNHANVIEN_GIOITINHChanged();
    partial void OnNHANVIEN_NTNSChanging(System.Nullable<System.DateTime> value);
    partial void OnNHANVIEN_NTNSChanged();
    partial void OnNHANVIEN_PHONEChanging(string value);
    partial void OnNHANVIEN_PHONEChanged();
    partial void OnNHANVIEN_DIACHIChanging(string value);
    partial void OnNHANVIEN_DIACHIChanged();
    partial void OnNHANVIEN_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnNHANVIEN_TRANGTHAIChanged();
    partial void OnTAIKHOAN_MANHANVIENChanging(string value);
    partial void OnTAIKHOAN_MANHANVIENChanged();
    #endregion
		
		public NHANVIEN()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._NHACUNGCAPs = new EntitySet<NHACUNGCAP>(new Action<NHACUNGCAP>(this.attach_NHACUNGCAPs), new Action<NHACUNGCAP>(this.detach_NHACUNGCAPs));
			this._TAIKHOAN = default(EntityRef<TAIKHOAN>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_MANHANVIEN", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string NHANVIEN_MANHANVIEN
		{
			get
			{
				return this._NHANVIEN_MANHANVIEN;
			}
			set
			{
				if ((this._NHANVIEN_MANHANVIEN != value))
				{
					this.OnNHANVIEN_MANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_MANHANVIEN = value;
					this.SendPropertyChanged("NHANVIEN_MANHANVIEN");
					this.OnNHANVIEN_MANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_HOVATENDEM", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NHANVIEN_HOVATENDEM
		{
			get
			{
				return this._NHANVIEN_HOVATENDEM;
			}
			set
			{
				if ((this._NHANVIEN_HOVATENDEM != value))
				{
					this.OnNHANVIEN_HOVATENDEMChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_HOVATENDEM = value;
					this.SendPropertyChanged("NHANVIEN_HOVATENDEM");
					this.OnNHANVIEN_HOVATENDEMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_TEN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NHANVIEN_TEN
		{
			get
			{
				return this._NHANVIEN_TEN;
			}
			set
			{
				if ((this._NHANVIEN_TEN != value))
				{
					this.OnNHANVIEN_TENChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_TEN = value;
					this.SendPropertyChanged("NHANVIEN_TEN");
					this.OnNHANVIEN_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_GIOITINH", DbType="NVarChar(4)")]
		public string NHANVIEN_GIOITINH
		{
			get
			{
				return this._NHANVIEN_GIOITINH;
			}
			set
			{
				if ((this._NHANVIEN_GIOITINH != value))
				{
					this.OnNHANVIEN_GIOITINHChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_GIOITINH = value;
					this.SendPropertyChanged("NHANVIEN_GIOITINH");
					this.OnNHANVIEN_GIOITINHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_NTNS", DbType="DateTime")]
		public System.Nullable<System.DateTime> NHANVIEN_NTNS
		{
			get
			{
				return this._NHANVIEN_NTNS;
			}
			set
			{
				if ((this._NHANVIEN_NTNS != value))
				{
					this.OnNHANVIEN_NTNSChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_NTNS = value;
					this.SendPropertyChanged("NHANVIEN_NTNS");
					this.OnNHANVIEN_NTNSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_PHONE", DbType="VarChar(11)")]
		public string NHANVIEN_PHONE
		{
			get
			{
				return this._NHANVIEN_PHONE;
			}
			set
			{
				if ((this._NHANVIEN_PHONE != value))
				{
					this.OnNHANVIEN_PHONEChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_PHONE = value;
					this.SendPropertyChanged("NHANVIEN_PHONE");
					this.OnNHANVIEN_PHONEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_DIACHI", DbType="NVarChar(200)")]
		public string NHANVIEN_DIACHI
		{
			get
			{
				return this._NHANVIEN_DIACHI;
			}
			set
			{
				if ((this._NHANVIEN_DIACHI != value))
				{
					this.OnNHANVIEN_DIACHIChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_DIACHI = value;
					this.SendPropertyChanged("NHANVIEN_DIACHI");
					this.OnNHANVIEN_DIACHIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> NHANVIEN_TRANGTHAI
		{
			get
			{
				return this._NHANVIEN_TRANGTHAI;
			}
			set
			{
				if ((this._NHANVIEN_TRANGTHAI != value))
				{
					this.OnNHANVIEN_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._NHANVIEN_TRANGTHAI = value;
					this.SendPropertyChanged("NHANVIEN_TRANGTHAI");
					this.OnNHANVIEN_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN_MANHANVIEN", DbType="VarChar(6)")]
		public string TAIKHOAN_MANHANVIEN
		{
			get
			{
				return this._TAIKHOAN_MANHANVIEN;
			}
			set
			{
				if ((this._TAIKHOAN_MANHANVIEN != value))
				{
					if (this._TAIKHOAN.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTAIKHOAN_MANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_MANHANVIEN = value;
					this.SendPropertyChanged("TAIKHOAN_MANHANVIEN");
					this.OnTAIKHOAN_MANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_HOADON", Storage="_HOADONs", ThisKey="NHANVIEN_MANHANVIEN", OtherKey="HOADON_MANV")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NHANVIEN_NHACUNGCAP", Storage="_NHACUNGCAPs", ThisKey="NHANVIEN_MANHANVIEN", OtherKey="MANHANVIEN")]
		public EntitySet<NHACUNGCAP> NHACUNGCAPs
		{
			get
			{
				return this._NHACUNGCAPs;
			}
			set
			{
				this._NHACUNGCAPs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_TAIKHOAN", ThisKey="TAIKHOAN_MANHANVIEN", OtherKey="TAIKHOAN_MANHANVIEN", IsForeignKey=true)]
		public TAIKHOAN TAIKHOAN
		{
			get
			{
				return this._TAIKHOAN.Entity;
			}
			set
			{
				TAIKHOAN previousValue = this._TAIKHOAN.Entity;
				if (((previousValue != value) 
							|| (this._TAIKHOAN.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._TAIKHOAN.Entity = null;
						previousValue.NHANVIENs.Remove(this);
					}
					this._TAIKHOAN.Entity = value;
					if ((value != null))
					{
						value.NHANVIENs.Add(this);
						this._TAIKHOAN_MANHANVIEN = value.TAIKHOAN_MANHANVIEN;
					}
					else
					{
						this._TAIKHOAN_MANHANVIEN = default(string);
					}
					this.SendPropertyChanged("TAIKHOAN");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
		
		private void attach_NHACUNGCAPs(NHACUNGCAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = this;
		}
		
		private void detach_NHACUNGCAPs(NHACUNGCAP entity)
		{
			this.SendPropertyChanging();
			entity.NHANVIEN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TAIKHOAN")]
	public partial class TAIKHOAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TAIKHOAN_MANHANVIEN;
		
		private string _TAIKHOAN_MATKHAU;
		
		private string _TAIKOHAN_LOAITAIKHOAN;
		
		private System.Nullable<byte> _TAIKHOAN_TRANGTHAI;
		
		private EntitySet<NHANVIEN> _NHANVIENs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTAIKHOAN_MANHANVIENChanging(string value);
    partial void OnTAIKHOAN_MANHANVIENChanged();
    partial void OnTAIKHOAN_MATKHAUChanging(string value);
    partial void OnTAIKHOAN_MATKHAUChanged();
    partial void OnTAIKOHAN_LOAITAIKHOANChanging(string value);
    partial void OnTAIKOHAN_LOAITAIKHOANChanged();
    partial void OnTAIKHOAN_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnTAIKHOAN_TRANGTHAIChanged();
    #endregion
		
		public TAIKHOAN()
		{
			this._NHANVIENs = new EntitySet<NHANVIEN>(new Action<NHANVIEN>(this.attach_NHANVIENs), new Action<NHANVIEN>(this.detach_NHANVIENs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN_MANHANVIEN", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TAIKHOAN_MANHANVIEN
		{
			get
			{
				return this._TAIKHOAN_MANHANVIEN;
			}
			set
			{
				if ((this._TAIKHOAN_MANHANVIEN != value))
				{
					this.OnTAIKHOAN_MANHANVIENChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_MANHANVIEN = value;
					this.SendPropertyChanged("TAIKHOAN_MANHANVIEN");
					this.OnTAIKHOAN_MANHANVIENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN_MATKHAU", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string TAIKHOAN_MATKHAU
		{
			get
			{
				return this._TAIKHOAN_MATKHAU;
			}
			set
			{
				if ((this._TAIKHOAN_MATKHAU != value))
				{
					this.OnTAIKHOAN_MATKHAUChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_MATKHAU = value;
					this.SendPropertyChanged("TAIKHOAN_MATKHAU");
					this.OnTAIKHOAN_MATKHAUChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKOHAN_LOAITAIKHOAN", DbType="NVarChar(10) NOT NULL", CanBeNull=false)]
		public string TAIKOHAN_LOAITAIKHOAN
		{
			get
			{
				return this._TAIKOHAN_LOAITAIKHOAN;
			}
			set
			{
				if ((this._TAIKOHAN_LOAITAIKHOAN != value))
				{
					this.OnTAIKOHAN_LOAITAIKHOANChanging(value);
					this.SendPropertyChanging();
					this._TAIKOHAN_LOAITAIKHOAN = value;
					this.SendPropertyChanged("TAIKOHAN_LOAITAIKHOAN");
					this.OnTAIKOHAN_LOAITAIKHOANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TAIKHOAN_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> TAIKHOAN_TRANGTHAI
		{
			get
			{
				return this._TAIKHOAN_TRANGTHAI;
			}
			set
			{
				if ((this._TAIKHOAN_TRANGTHAI != value))
				{
					this.OnTAIKHOAN_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TAIKHOAN_TRANGTHAI = value;
					this.SendPropertyChanged("TAIKHOAN_TRANGTHAI");
					this.OnTAIKHOAN_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TAIKHOAN_NHANVIEN", Storage="_NHANVIENs", ThisKey="TAIKHOAN_MANHANVIEN", OtherKey="TAIKHOAN_MANHANVIEN")]
		public EntitySet<NHANVIEN> NHANVIENs
		{
			get
			{
				return this._NHANVIENs;
			}
			set
			{
				this._NHANVIENs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = this;
		}
		
		private void detach_NHANVIENs(NHANVIEN entity)
		{
			this.SendPropertyChanging();
			entity.TAIKHOAN = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THANHVIEN")]
	public partial class THANHVIEN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _THANHVIEN_MATV;
		
		private System.Nullable<int> _DIEMTICHLUY;
		
		private string _THANHVIEN_HOTEN;
		
		private string _THANHVIEN_SDT;
		
		private System.DateTime _THANHVIEN_NGAYGIANHAP;
		
		private string _THANHVIEN_EMAIL;
		
		private System.Nullable<byte> _THANHVIEN_TRANGTHAI;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTHANHVIEN_MATVChanging(string value);
    partial void OnTHANHVIEN_MATVChanged();
    partial void OnDIEMTICHLUYChanging(System.Nullable<int> value);
    partial void OnDIEMTICHLUYChanged();
    partial void OnTHANHVIEN_HOTENChanging(string value);
    partial void OnTHANHVIEN_HOTENChanged();
    partial void OnTHANHVIEN_SDTChanging(string value);
    partial void OnTHANHVIEN_SDTChanged();
    partial void OnTHANHVIEN_NGAYGIANHAPChanging(System.DateTime value);
    partial void OnTHANHVIEN_NGAYGIANHAPChanged();
    partial void OnTHANHVIEN_EMAILChanging(string value);
    partial void OnTHANHVIEN_EMAILChanged();
    partial void OnTHANHVIEN_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnTHANHVIEN_TRANGTHAIChanged();
    #endregion
		
		public THANHVIEN()
		{
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_MATV", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string THANHVIEN_MATV
		{
			get
			{
				return this._THANHVIEN_MATV;
			}
			set
			{
				if ((this._THANHVIEN_MATV != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnTHANHVIEN_MATVChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_MATV = value;
					this.SendPropertyChanged("THANHVIEN_MATV");
					this.OnTHANHVIEN_MATVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIEMTICHLUY", DbType="Int")]
		public System.Nullable<int> DIEMTICHLUY
		{
			get
			{
				return this._DIEMTICHLUY;
			}
			set
			{
				if ((this._DIEMTICHLUY != value))
				{
					this.OnDIEMTICHLUYChanging(value);
					this.SendPropertyChanging();
					this._DIEMTICHLUY = value;
					this.SendPropertyChanged("DIEMTICHLUY");
					this.OnDIEMTICHLUYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_HOTEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string THANHVIEN_HOTEN
		{
			get
			{
				return this._THANHVIEN_HOTEN;
			}
			set
			{
				if ((this._THANHVIEN_HOTEN != value))
				{
					this.OnTHANHVIEN_HOTENChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_HOTEN = value;
					this.SendPropertyChanged("THANHVIEN_HOTEN");
					this.OnTHANHVIEN_HOTENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_SDT", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string THANHVIEN_SDT
		{
			get
			{
				return this._THANHVIEN_SDT;
			}
			set
			{
				if ((this._THANHVIEN_SDT != value))
				{
					this.OnTHANHVIEN_SDTChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_SDT = value;
					this.SendPropertyChanged("THANHVIEN_SDT");
					this.OnTHANHVIEN_SDTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_NGAYGIANHAP", DbType="DateTime NOT NULL")]
		public System.DateTime THANHVIEN_NGAYGIANHAP
		{
			get
			{
				return this._THANHVIEN_NGAYGIANHAP;
			}
			set
			{
				if ((this._THANHVIEN_NGAYGIANHAP != value))
				{
					this.OnTHANHVIEN_NGAYGIANHAPChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_NGAYGIANHAP = value;
					this.SendPropertyChanged("THANHVIEN_NGAYGIANHAP");
					this.OnTHANHVIEN_NGAYGIANHAPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_EMAIL", DbType="NVarChar(255)")]
		public string THANHVIEN_EMAIL
		{
			get
			{
				return this._THANHVIEN_EMAIL;
			}
			set
			{
				if ((this._THANHVIEN_EMAIL != value))
				{
					this.OnTHANHVIEN_EMAILChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_EMAIL = value;
					this.SendPropertyChanged("THANHVIEN_EMAIL");
					this.OnTHANHVIEN_EMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THANHVIEN_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> THANHVIEN_TRANGTHAI
		{
			get
			{
				return this._THANHVIEN_TRANGTHAI;
			}
			set
			{
				if ((this._THANHVIEN_TRANGTHAI != value))
				{
					this.OnTHANHVIEN_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._THANHVIEN_TRANGTHAI = value;
					this.SendPropertyChanged("THANHVIEN_TRANGTHAI");
					this.OnTHANHVIEN_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THANHVIEN", Storage="_KHACHHANG", ThisKey="THANHVIEN_MATV", OtherKey="KHACHHANG_MAKHACH", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.THANHVIEN = null;
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.THANHVIEN = this;
						this._THANHVIEN_MATV = value.KHACHHANG_MAKHACH;
					}
					else
					{
						this._THANHVIEN_MATV = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TRASUA")]
	public partial class TRASUA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _TRASUA_MATS;
		
		private string _TRASUA_TEN;
		
		private decimal _TRASUA_GIA;
		
		private System.DateTime _TRASUA_NGAYTAO;
		
		private string _TRASUA_MOTA;
		
		private System.Nullable<byte> _TRASUA_TRANGTHAI;
		
		private EntitySet<CHITIET_HOADON> _CHITIET_HOADONs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnTRASUA_MATSChanging(string value);
    partial void OnTRASUA_MATSChanged();
    partial void OnTRASUA_TENChanging(string value);
    partial void OnTRASUA_TENChanged();
    partial void OnTRASUA_GIAChanging(decimal value);
    partial void OnTRASUA_GIAChanged();
    partial void OnTRASUA_NGAYTAOChanging(System.DateTime value);
    partial void OnTRASUA_NGAYTAOChanged();
    partial void OnTRASUA_MOTAChanging(string value);
    partial void OnTRASUA_MOTAChanged();
    partial void OnTRASUA_TRANGTHAIChanging(System.Nullable<byte> value);
    partial void OnTRASUA_TRANGTHAIChanged();
    #endregion
		
		public TRASUA()
		{
			this._CHITIET_HOADONs = new EntitySet<CHITIET_HOADON>(new Action<CHITIET_HOADON>(this.attach_CHITIET_HOADONs), new Action<CHITIET_HOADON>(this.detach_CHITIET_HOADONs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MATS", DbType="VarChar(6) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string TRASUA_MATS
		{
			get
			{
				return this._TRASUA_MATS;
			}
			set
			{
				if ((this._TRASUA_MATS != value))
				{
					this.OnTRASUA_MATSChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_MATS = value;
					this.SendPropertyChanged("TRASUA_MATS");
					this.OnTRASUA_MATSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TRASUA_TEN
		{
			get
			{
				return this._TRASUA_TEN;
			}
			set
			{
				if ((this._TRASUA_TEN != value))
				{
					this.OnTRASUA_TENChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_TEN = value;
					this.SendPropertyChanged("TRASUA_TEN");
					this.OnTRASUA_TENChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_GIA", DbType="Money NOT NULL")]
		public decimal TRASUA_GIA
		{
			get
			{
				return this._TRASUA_GIA;
			}
			set
			{
				if ((this._TRASUA_GIA != value))
				{
					this.OnTRASUA_GIAChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_GIA = value;
					this.SendPropertyChanged("TRASUA_GIA");
					this.OnTRASUA_GIAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_NGAYTAO", DbType="DateTime NOT NULL")]
		public System.DateTime TRASUA_NGAYTAO
		{
			get
			{
				return this._TRASUA_NGAYTAO;
			}
			set
			{
				if ((this._TRASUA_NGAYTAO != value))
				{
					this.OnTRASUA_NGAYTAOChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_NGAYTAO = value;
					this.SendPropertyChanged("TRASUA_NGAYTAO");
					this.OnTRASUA_NGAYTAOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MOTA", DbType="NVarChar(100)")]
		public string TRASUA_MOTA
		{
			get
			{
				return this._TRASUA_MOTA;
			}
			set
			{
				if ((this._TRASUA_MOTA != value))
				{
					this.OnTRASUA_MOTAChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_MOTA = value;
					this.SendPropertyChanged("TRASUA_MOTA");
					this.OnTRASUA_MOTAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> TRASUA_TRANGTHAI
		{
			get
			{
				return this._TRASUA_TRANGTHAI;
			}
			set
			{
				if ((this._TRASUA_TRANGTHAI != value))
				{
					this.OnTRASUA_TRANGTHAIChanging(value);
					this.SendPropertyChanging();
					this._TRASUA_TRANGTHAI = value;
					this.SendPropertyChanged("TRASUA_TRANGTHAI");
					this.OnTRASUA_TRANGTHAIChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="TRASUA_CHITIET_HOADON", Storage="_CHITIET_HOADONs", ThisKey="TRASUA_MATS", OtherKey="CHITIET_HOADON_MATS")]
		public EntitySet<CHITIET_HOADON> CHITIET_HOADONs
		{
			get
			{
				return this._CHITIET_HOADONs;
			}
			set
			{
				this._CHITIET_HOADONs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CHITIET_HOADONs(CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TRASUA = this;
		}
		
		private void detach_CHITIET_HOADONs(CHITIET_HOADON entity)
		{
			this.SendPropertyChanging();
			entity.TRASUA = null;
		}
	}
	
	public partial class SP_TimMaSPResult
	{
		
		private string _TRASUA_MATS;
		
		private string _TRASUA_TEN;
		
		private decimal _TRASUA_GIA;
		
		private System.DateTime _TRASUA_NGAYTAO;
		
		private string _TRASUA_MOTA;
		
		private System.Nullable<byte> _TRASUA_TRANGTHAI;
		
		public SP_TimMaSPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MATS", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string TRASUA_MATS
		{
			get
			{
				return this._TRASUA_MATS;
			}
			set
			{
				if ((this._TRASUA_MATS != value))
				{
					this._TRASUA_MATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TRASUA_TEN
		{
			get
			{
				return this._TRASUA_TEN;
			}
			set
			{
				if ((this._TRASUA_TEN != value))
				{
					this._TRASUA_TEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_GIA", DbType="Money NOT NULL")]
		public decimal TRASUA_GIA
		{
			get
			{
				return this._TRASUA_GIA;
			}
			set
			{
				if ((this._TRASUA_GIA != value))
				{
					this._TRASUA_GIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_NGAYTAO", DbType="DateTime NOT NULL")]
		public System.DateTime TRASUA_NGAYTAO
		{
			get
			{
				return this._TRASUA_NGAYTAO;
			}
			set
			{
				if ((this._TRASUA_NGAYTAO != value))
				{
					this._TRASUA_NGAYTAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MOTA", DbType="NVarChar(100)")]
		public string TRASUA_MOTA
		{
			get
			{
				return this._TRASUA_MOTA;
			}
			set
			{
				if ((this._TRASUA_MOTA != value))
				{
					this._TRASUA_MOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> TRASUA_TRANGTHAI
		{
			get
			{
				return this._TRASUA_TRANGTHAI;
			}
			set
			{
				if ((this._TRASUA_TRANGTHAI != value))
				{
					this._TRASUA_TRANGTHAI = value;
				}
			}
		}
	}
	
	public partial class SP_DangNhapResult
	{
		
		private int _code;
		
		private string _NHANVIEN_HOVATENDEM;
		
		private string _NHANVIEN_TEN;
		
		private string _NHANVIEN_LOAINV;
		
		public SP_DangNhapResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Int NOT NULL")]
		public int code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_HOVATENDEM", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NHANVIEN_HOVATENDEM
		{
			get
			{
				return this._NHANVIEN_HOVATENDEM;
			}
			set
			{
				if ((this._NHANVIEN_HOVATENDEM != value))
				{
					this._NHANVIEN_HOVATENDEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_TEN", DbType="NVarChar(30) NOT NULL", CanBeNull=false)]
		public string NHANVIEN_TEN
		{
			get
			{
				return this._NHANVIEN_TEN;
			}
			set
			{
				if ((this._NHANVIEN_TEN != value))
				{
					this._NHANVIEN_TEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHANVIEN_LOAINV", DbType="NVarChar(20)")]
		public string NHANVIEN_LOAINV
		{
			get
			{
				return this._NHANVIEN_LOAINV;
			}
			set
			{
				if ((this._NHANVIEN_LOAINV != value))
				{
					this._NHANVIEN_LOAINV = value;
				}
			}
		}
	}
	
	public partial class SP_LayDSNCCResult
	{
		
		private string _NHACUNGCAP_MANCC;
		
		private string _NHACUNGCAP_TEN;
		
		private string _NHACUNGCAP_SDT;
		
		private string _NHACUNGCAP_DIACHI;
		
		private System.Nullable<byte> _NHACUNGCAP_TRANGTHAI;
		
		private string _NHACUNGCAP_MATHANG;
		
		public SP_LayDSNCCResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_MANCC", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string NHACUNGCAP_MANCC
		{
			get
			{
				return this._NHACUNGCAP_MANCC;
			}
			set
			{
				if ((this._NHACUNGCAP_MANCC != value))
				{
					this._NHACUNGCAP_MANCC = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_TEN", DbType="NVarChar(50)")]
		public string NHACUNGCAP_TEN
		{
			get
			{
				return this._NHACUNGCAP_TEN;
			}
			set
			{
				if ((this._NHACUNGCAP_TEN != value))
				{
					this._NHACUNGCAP_TEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_SDT", DbType="VarChar(11)")]
		public string NHACUNGCAP_SDT
		{
			get
			{
				return this._NHACUNGCAP_SDT;
			}
			set
			{
				if ((this._NHACUNGCAP_SDT != value))
				{
					this._NHACUNGCAP_SDT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_DIACHI", DbType="NVarChar(50)")]
		public string NHACUNGCAP_DIACHI
		{
			get
			{
				return this._NHACUNGCAP_DIACHI;
			}
			set
			{
				if ((this._NHACUNGCAP_DIACHI != value))
				{
					this._NHACUNGCAP_DIACHI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> NHACUNGCAP_TRANGTHAI
		{
			get
			{
				return this._NHACUNGCAP_TRANGTHAI;
			}
			set
			{
				if ((this._NHACUNGCAP_TRANGTHAI != value))
				{
					this._NHACUNGCAP_TRANGTHAI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NHACUNGCAP_MATHANG", DbType="NVarChar(255)")]
		public string NHACUNGCAP_MATHANG
		{
			get
			{
				return this._NHACUNGCAP_MATHANG;
			}
			set
			{
				if ((this._NHACUNGCAP_MATHANG != value))
				{
					this._NHACUNGCAP_MATHANG = value;
				}
			}
		}
	}
	
	public partial class SP_LayDSSPResult
	{
		
		private string _TRASUA_MATS;
		
		private string _TRASUA_TEN;
		
		private decimal _TRASUA_GIA;
		
		private System.DateTime _TRASUA_NGAYTAO;
		
		private string _TRASUA_MOTA;
		
		private System.Nullable<byte> _TRASUA_TRANGTHAI;
		
		public SP_LayDSSPResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MATS", DbType="VarChar(6) NOT NULL", CanBeNull=false)]
		public string TRASUA_MATS
		{
			get
			{
				return this._TRASUA_MATS;
			}
			set
			{
				if ((this._TRASUA_MATS != value))
				{
					this._TRASUA_MATS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TEN", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string TRASUA_TEN
		{
			get
			{
				return this._TRASUA_TEN;
			}
			set
			{
				if ((this._TRASUA_TEN != value))
				{
					this._TRASUA_TEN = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_GIA", DbType="Money NOT NULL")]
		public decimal TRASUA_GIA
		{
			get
			{
				return this._TRASUA_GIA;
			}
			set
			{
				if ((this._TRASUA_GIA != value))
				{
					this._TRASUA_GIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_NGAYTAO", DbType="DateTime NOT NULL")]
		public System.DateTime TRASUA_NGAYTAO
		{
			get
			{
				return this._TRASUA_NGAYTAO;
			}
			set
			{
				if ((this._TRASUA_NGAYTAO != value))
				{
					this._TRASUA_NGAYTAO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_MOTA", DbType="NVarChar(100)")]
		public string TRASUA_MOTA
		{
			get
			{
				return this._TRASUA_MOTA;
			}
			set
			{
				if ((this._TRASUA_MOTA != value))
				{
					this._TRASUA_MOTA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_TRANGTHAI", DbType="TinyInt")]
		public System.Nullable<byte> TRASUA_TRANGTHAI
		{
			get
			{
				return this._TRASUA_TRANGTHAI;
			}
			set
			{
				if ((this._TRASUA_TRANGTHAI != value))
				{
					this._TRASUA_TRANGTHAI = value;
				}
			}
		}
	}
	
	public partial class SP_KiemTraMatHangResult
	{
		
		private int _code;
		
		public SP_KiemTraMatHangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_code", DbType="Int NOT NULL")]
		public int code
		{
			get
			{
				return this._code;
			}
			set
			{
				if ((this._code != value))
				{
					this._code = value;
				}
			}
		}
	}
	
	public partial class SP_BanHangResult
	{
		
		private decimal _TRASUA_GIA;
		
		public SP_BanHangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TRASUA_GIA", DbType="Money NOT NULL")]
		public decimal TRASUA_GIA
		{
			get
			{
				return this._TRASUA_GIA;
			}
			set
			{
				if ((this._TRASUA_GIA != value))
				{
					this._TRASUA_GIA = value;
				}
			}
		}
	}
	
	public partial class SP_HienThiChiTietHoaDonResult
	{
		
		private string _CHITIET_HOADON_TENSP;
		
		private int _CHITIET_HOADON_SOLUONG;
		
		private decimal _CHITIET_HOADON_DONGIA;
		
		private System.Nullable<decimal> _total;
		
		public SP_HienThiChiTietHoaDonResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_TENSP", DbType="NVarChar(100)")]
		public string CHITIET_HOADON_TENSP
		{
			get
			{
				return this._CHITIET_HOADON_TENSP;
			}
			set
			{
				if ((this._CHITIET_HOADON_TENSP != value))
				{
					this._CHITIET_HOADON_TENSP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_SOLUONG", DbType="Int NOT NULL")]
		public int CHITIET_HOADON_SOLUONG
		{
			get
			{
				return this._CHITIET_HOADON_SOLUONG;
			}
			set
			{
				if ((this._CHITIET_HOADON_SOLUONG != value))
				{
					this._CHITIET_HOADON_SOLUONG = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHITIET_HOADON_DONGIA", DbType="Money NOT NULL")]
		public decimal CHITIET_HOADON_DONGIA
		{
			get
			{
				return this._CHITIET_HOADON_DONGIA;
			}
			set
			{
				if ((this._CHITIET_HOADON_DONGIA != value))
				{
					this._CHITIET_HOADON_DONGIA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this._total = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
