//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HOADON
    {
        public string CHITIET_HOADON_MAHOADON { get; set; }
        public string CHITIET_HOADON_MATS { get; set; }
        public string CHITIET_HOADON_TENSP { get; set; }
        public int CHITIET_HOADON_SOLUONG { get; set; }
        public decimal CHITIET_HOADON_DONGIA { get; set; }
        public string MACTHD { get; set; }
    
        public virtual TRASUA TRASUA { get; set; }
        public virtual HOADON HOADON { get; set; }
    }
}
