//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADON
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADON()
        {
            this.CHITIET_HOADON = new HashSet<CHITIET_HOADON>();
        }
    
        public string HOADON_MAHOADON { get; set; }
        public System.DateTime HOADON_NGAYLAP { get; set; }
        public Nullable<byte> HOADON_TRANGTHAI { get; set; }
        public Nullable<decimal> HOADON_KHACHTRA { get; set; }
        public Nullable<decimal> HOADON_THANHTIEN { get; set; }
        public Nullable<decimal> HOADON_THOILAI { get; set; }
        public string HOADON_MAKH { get; set; }
        public string HOADON_MANV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HOADON> CHITIET_HOADON { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
