//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KHACHHANG()
        {
            this.HOADONs = new HashSet<HOADON>();
        }
    
        public string KHACHHANG_MAKHACH { get; set; }
        public string KHACHHANG_HOTENDEM { get; set; }
        public string KHACHHANG_TEN { get; set; }
        public string KHACHANG_SODIENTHOAI { get; set; }
        public Nullable<System.DateTime> KHACHANG_NGAYSINH { get; set; }
        public string KHACHHANG_DIACHI { get; set; }
        public string KHACHHANG_GIOITINH { get; set; }
        public Nullable<byte> KHACHHANG_TRANGTHAI { get; set; }
        public string KHACHHANG_LOAIKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        public virtual LOAIKH LOAIKH { get; set; }
        public virtual THANHVIEN THANHVIEN { get; set; }
    }
}
