//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NGUYENLIEU
    {
        public string NGUYENLIEU_MANL { get; set; }
        public string NGUYENLIEU_TEN { get; set; }
        public System.DateTime NGUYENLIEU_NGAYNHAP { get; set; }
        public System.DateTime NGUYENLIEU_HANSD { get; set; }
        public Nullable<int> NGUYENLIEU_SOLUONGTON { get; set; }
        public string NGUYENLIEU_MOTA { get; set; }
        public Nullable<byte> NGUYENLIEU_TRANGTHAI { get; set; }
        public string NGUYENLIEU_TENNCC { get; set; }
    }
}
