//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHACUNGCAP
    {
        public string NHACUNGCAP_MANCC { get; set; }
        public string NHACUNGCAP_TEN { get; set; }
        public string NHACUNGCAP_SDT { get; set; }
        public string NHACUNGCAP_DIACHI { get; set; }
        public Nullable<byte> NHACUNGCAP_TRANGTHAI { get; set; }
        public string NHACUNGCAP_MATHANG { get; set; }
        public string MANHANVIEN { get; set; }
    
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
