//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANVIEN
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANVIEN()
        {
            this.HOADONs = new HashSet<HOADON>();
            this.NHACUNGCAPs = new HashSet<NHACUNGCAP>();
        }
    
        public string NHANVIEN_MANHANVIEN { get; set; }
        public string NHANVIEN_HOVATENDEM { get; set; }
        public string NHANVIEN_TEN { get; set; }
        public string NHANVIEN_GIOITINH { get; set; }
        public Nullable<System.DateTime> NHANVIEN_NTNS { get; set; }
        public string NHANVIEN_PHONE { get; set; }
        public string NHANVIEN_DIACHI { get; set; }
        public Nullable<byte> NHANVIEN_TRANGTHAI { get; set; }
        public string NHANVIEN_EMAIL { get; set; }
        public string NHANVIEN_LOAINV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HOADON> HOADONs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
    }
}
