//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TAIKHOAN
    {
        public string TAIKHOAN_MANHANVIEN { get; set; }
        public string TAIKHOAN_MATKHAU { get; set; }
        public string TAIKHOAN_MALOAI { get; set; }
        public Nullable<byte> TAIKHOAN_TRANGTHAI { get; set; }
        public System.DateTime TAIKHOAN_NGAYTAO { get; set; }
        public string TAIKHOAN_GHICHU { get; set; }
    
        public virtual LOAITAIKHOAN LOAITAIKHOAN { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
    }
}
