//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class THANHVIEN
    {
        public string THANHVIEN_MATV { get; set; }
        public Nullable<int> DIEMTICHLUY { get; set; }
        public string THANHVIEN_HOTEN { get; set; }
        public string THANHVIEN_SDT { get; set; }
        public System.DateTime THANHVIEN_NGAYGIANHAP { get; set; }
        public string THANHVIEN_EMAIL { get; set; }
        public Nullable<byte> THANHVIEN_TRANGTHAI { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
    }
}
